name: Build and Push to ACR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: add-task
      IMAGE_TAG: v0
      IMAGE_NAME1: micro-ui
      IMAGE_TAG1: v0
      ACR_NAME: devtodoacrwestus
      ACR_LOGIN_SERVER: devtodoacrwestus.azurecr.io
      RESOURCE_GROUP: psddg
      AKS_NAME: devtodoakswestus

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 🔐 Azure Login
      - name: Azure Login
        uses: Azure/login@v2
        with:
          client-id: 6c2702c6-118e-4640-aba9-86e61333ba0d
          tenant-id: 1658eae6-9066-4c87-8f0e-22a840432c57
          subscription-id: 20cadb7c-62d8-4c57-9b49-63ebd307c63e

      # 🔑 Login to ACR
      - name: Login to ACR
        run: az acr login --name $ACR_NAME

      # 🔥 BUILD + PUSH ADD SERVICE
      - name: Build Add Image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG -f app/Add/Dockerfile app

      - name: Tag Add Image
        run: docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Add Image
        run: docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      # 🔥 BUILD + PUSH MICRO SERVICE
      - name: Build Micro Image
        run: docker build -t $IMAGE_NAME1:$IMAGE_TAG1 -f app/Micro/Dockerfile app/Micro

      - name: Tag Micro Image
        run: docker tag $IMAGE_NAME1:$IMAGE_TAG1 $ACR_LOGIN_SERVER/$IMAGE_NAME1:$IMAGE_TAG1

      - name: Push Micro Image
        run: docker push $ACR_LOGIN_SERVER/$IMAGE_NAME1:$IMAGE_TAG1

      # 📦 Install kubectl (IMPORTANT)
      - name: Install kubectl
        run: |
          az aks install-cli

      # 🚀 SET AKS CONTEXT
      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group $RESOURCE_GROUP \
            --name $AKS_NAME \
            --overwrite-existing

      //# 🚀 DEPLOY TO AKS
      //- name: Deploy to AKS
      //  run: |
      //    kubectl apply -f app/manifest/
      //    kubectl get pods -A
      
      # 🚀 DEPLOY TO AKS
      - name: Deploy to AKS using ARGO CD
        run: |
          kubectl apply -f application.yaml
          kubectl get applications -n argocd
          kubectl port-forward svc/argocd-server -n argocd 8080:443
          https://localhost:8080